version: 2

sources:
    - name: gz_raw_data
      description: greenweez raw data source
      tables:
        - name: product
          description: products of greenweez
          columns:
            - name: products_id
              description: products identification 
              tests:
              - unique:
                  column_name: "(products_id)"
              - not_null:
                  column_name: "(products_id)"
        - name: ship
          description: shipping of greenweez
          columns:
            - name: orders_id
              description: orders identification
              tests:
              - unique:
                  column_name: "(orders_id)"
              - not_null:
                  column_name: "(orders_id)"
        - name: sales
          description: sales of greenweez
          tests:
            - unique:
                column_name: "(orders_id || '-' || pdt_id)"
        - name: adwords
          description: adwords campaign
          tests:
            - unique:
                column_name: "(date_date || '-' || campaign_key)"
            - not_null:
                column_name: "(date_date || '-' || campaign_key)"
        - name: bing
          description: bing campaign
          tests:
            - unique:
                column_name: "(date_date || '-' || campaign_key)"
            - not_null:
                column_name: "(date_date || '-' || campaign_key)"
        - name: criteo
          description: criteo campaign
          tests:
            - unique:
                column_name: "(date_date || '-' || campaign_key)"
            - not_null:
                column_name: "(date_date || '-' || campaign_key)"
        - name: facebook
          description: facebook campaign
          tests:
            - unique:
                column_name: "(date_date || '-' || campaign_key)"
            - not_null:
                column_name: "(date_date || '-' || campaign_key)"

models:
   - name: int_campaigns
     description: merged all campaigns
     tests:
      - unique:
          column_name: "(date_date || '-' || campaign_key)"
      - not_null:
          column_name: paid_source
      - not_null:
          column_name: campaign_name
   - name: stg_gz_raw_data__product
     description: list of products
     columns: 
        - name: products_id
          description: primary key
          tests:
            - unique
            - not_null
   - name: stg_gz_raw_data__ship
     description: list of shippings
     columns: 
      - name: orders_id
        description: primary key
        tests:
          - unique
          - not_null
   - name: stg_gz_raw_data__sales
     description: list of sales
     columns: 
      - name: clave
        description: primary key
        tests:
          - unique
          - not_null
   - name: int_sales__margin
     description: margin calcultation per order line / product sale
     columns:
      - name: margin
        description: Margin = Revenue - Purchase_cost
      - name: Purchase_cost
        description: Purchase_cost = Quantity * Purchase_price
     tests:
      - unique
      - not_null
   - name: int_orders__margin
     description: margin calcultation per order 
     columns:
      - name: orders_id
        description: primary key
      - name: margin
        description: Margin = Revenue - Purchase_cost
      - name: Purchase_cost
        description: Purchase_cost = Quantity * Purchase_price 
      - name: date_date
        description: date of the order
      - name: revenue
        description: sum of revenue per order 
      - name: quantity
        description: sum of quantity per order
     tests:
      - unique
      - not_null
   - name: int_orders__operational
     description: operational margin calcultation per order 
     columns:
      - name: operational_margin 
        description: Operational margin = margin + shipping fee - log_cost - ship_cost
     tests:
      - unique
      - not_null
   - name: finance_days
     description: finance calculation per days
   - name: int_campaigns_day
     description: per_day
     tests:
      - unique:
          column_name: date_date
      - not_null:
          column_name: date_date
